name: meu_financeiro_pessoal
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    # --- DEPENDÊNCIAS DO BANCO DE DADOS ---
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3
  
  cupertino_icons: ^1.0.2
  fl_chart: ^1.0.0
  intl: ^0.19.0 # CORRIGIDO: Esta era a linha com a versão inválida.
  flutter_riverpod: ^2.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true